(function(){'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)]; let data=null, view='dashboard', filter='open', editing=null, selectedNote=null, timer, history=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=p=>p+'-'+Date.now().toString(36)+Math.random().toString(36).slice(2,6);
async function request(body,method='POST'){let r=await fetch('/api/planner',{method,headers:{'Content-Type':'application/json'},credentials:'same-origin',cache:'no-store',body:method==='POST'?JSON.stringify(body):undefined}),j=await r.json().catch(()=>({error:'bad_response'}));if(!r.ok){let e=new Error(j.error);e.status=r.status;e.server=j.data;throw e}return j}
function notify(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout($('#toast').t);$('#toast').t=setTimeout(()=>$('#toast').classList.remove('show'),2200)}
function sync(s,bad=false){$('#syncState span').textContent=s;$('#syncState i').style.background=bad?'#e75a5a':'#20c988'}
function save(now=false){clearTimeout(timer);sync('Saving…');timer=setTimeout(async()=>{try{let r=await request({action:'save',revision:data.revision,data});data=r.data;sync('Saved to cloud');render()}catch(e){if(e.status===409&&e.server){data=e.server;render();sync('Newer copy loaded',true);notify('A newer server copy was loaded.')}else{sync(e.message==='storage_not_configured'?'Cloud not configured':'Save failed',true);notify('Change not saved. Try again.')}}},now?0:550)}
const classFor=id=>data.classes.find(c=>c.id===id), fmt=d=>d?new Date(d).toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'}):'No due date';
function openApp(){let n=new Date;$('#loginView').hidden=true;$('#app').hidden=false;$('#dateLine').textContent=n.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});$('#dayPart').textContent=n.getHours()<12?'morning':n.getHours()<18?'afternoon':'evening';render()}
async function initial(){try{let r=await request(null,'GET');data=r.data;openApp();sync('Saved to cloud')}catch(e){if(e.status!==401)$('#loginError').textContent=e.message==='storage_not_configured'?'Connect planner storage in Vercel.':'Planner is temporarily unavailable.'}}
function changeView(v){view=v;$$('[data-panel]').forEach(p=>p.classList.toggle('active',p.dataset.panel===v));$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('#viewTitle').textContent={dashboard:'Overview',tasks:'Assignments',schedule:'Weekly schedule',classes:'Classes',notes:'Notes'}[v];$('#app').classList.remove('menu-open');render()}
function taskRow(t){let c=classFor(t.classId);return `<div class="task-row ${t.completed?'completed':''}"><button class="check ${t.completed?'done':''}" data-check="${esc(t.id)}">${t.completed?'✓':''}</button><div class="item-copy"><b>${esc(t.title)}</b><small>${esc(c?c.name:'Personal')} · ${esc(fmt(t.due))}</small></div><span class="priority">${esc(t.priority)}</span><button class="plain" data-edit-task="${esc(t.id)}">•••</button></div>`}
function renderDashboard(){let now=new Date,today=now.toISOString().slice(0,10),end=new Date(now);end.setDate(end.getDate()+7);let open=data.tasks.filter(t=>!t.completed),due=open.filter(t=>t.due?.slice(0,10)===today),week=open.filter(t=>{let d=new Date(t.due);return t.due&&d>=new Date(today)&&d<=end}),done=data.tasks.filter(t=>t.completed).length,pct=data.tasks.length?Math.round(done/data.tasks.length*100):0;$('#dueToday').textContent=due.length;$('#dueTodaySub').textContent=due.length?'Needs attention':'Nothing waiting';$('#dueWeek').textContent=week.length;$('#completedCount').textContent=done;$('#classCount').textContent=data.classes.length;$('#ringValue').textContent=pct+'%';$('#ringProgress').style.strokeDashoffset=245-245*pct/100;$('#welcomeSub').textContent=due.length?`${due.length} assignment${due.length===1?'':'s'} due today.`:'You have room to get ahead today.';
 let day=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][now.getDay()],classes=data.classes.filter(c=>c.days.includes(day)).sort((a,b)=>a.start.localeCompare(b.start));$('#todayAgenda').innerHTML=classes.length?classes.map(c=>`<div class="agenda-item"><span class="agenda-time">${esc(c.start||'Anytime')}</span><i class="class-dot" style="--c:${esc(c.color)}"></i><div class="item-copy"><b>${esc(c.name)}</b><small>${esc(c.room||c.code||'Class')}${c.end?' · until '+esc(c.end):''}</small></div></div>`).join(''):'<div class="empty"><b>No classes today</b><p>Use the space to study or recharge.</p></div>';
 let focus=open.sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999')).slice(0,4);$('#focusTasks').innerHTML=focus.length?focus.map(taskRow).join(''):'<div class="empty"><b>Your queue is clear</b><p>Add an assignment when you get one.</p></div>';renderWeek()}
function renderWeek(){let s=new Date,n=s.getDay()||7;s.setHours(0,0,0,0);s.setDate(s.getDate()-n+1);let out='';for(let i=0;i<7;i++){let d=new Date(s);d.setDate(s.getDate()+i);let key=d.toISOString().slice(0,10),items=data.tasks.filter(t=>t.due?.slice(0,10)===key);out+=`<div class="week-day ${key===new Date().toISOString().slice(0,10)?'today':''}"><header><span>${d.toLocaleDateString(undefined,{weekday:'short'})}</span><b>${d.getDate()}</b></header>${items.slice(0,4).map(t=>`<i title="${esc(t.title)}" style="--c:${classFor(t.classId)?.color||'#9095a3'}"></i>`).join('')}</div>`}$('#weekDays').innerHTML=out}
function renderTasks(){let cf=$('#taskClassFilter').value,list=data.tasks.filter(t=>(filter==='all'||filter==='open'&&!t.completed||filter==='completed'&&t.completed)&&(!cf||t.classId===cf)).sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999'));$('#taskList').innerHTML=list.length?list.map(taskRow).join(''):'<div class="empty"><b>No assignments here</b><p>Change the filter or add one.</p></div>'}
function renderSchedule(){let days=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];$('#scheduleHead').innerHTML='<div></div>'+days.map(d=>`<div><b>${d}</b></div>`).join('');let body='<div class="time-axis">';for(let h=8;h<=18;h++)body+=`<span>${(h+11)%12+1}${h<12?' AM':' PM'}</span>`;body+='</div>';days.forEach(day=>{body+='<div class="day-col">'+data.classes.filter(c=>c.days.includes(day)).map(c=>{let s=+(c.start||'08:00').slice(0,2)+(+(c.start||'08:00').slice(3)/60),e=+(c.end||'09:00').slice(0,2)+(+(c.end||'09:00').slice(3)/60);return `<div class="class-block" style="--c:${c.color};top:${Math.max(0,(s-8)*60)}px;height:${Math.max(40,(e-s)*60)}px"><b>${esc(c.name)}</b><span>${esc(c.start)}–${esc(c.end)}</span></div>`}).join('')+'</div>'});$('#scheduleBody').innerHTML=body}
function renderClasses(){$('#classGrid').innerHTML=data.classes.map(c=>`<article class="class-card" style="--c:${esc(c.color)}"><button data-edit-class="${esc(c.id)}">•••</button><h3>${esc(c.name)}</h3><p>${esc(c.code||'No class code')}</p><footer><b>${esc(c.days.join(' · ')||'No meeting days')}</b><br>${esc(c.start||'No time')}${c.end?' – '+esc(c.end):''}${c.room?'<br>'+esc(c.room):''}</footer></article>`).join('')||'<div class="empty"><b>No classes yet</b></div>'}
function renderNotes(){$('#notesList').innerHTML=data.notes.map(n=>`<button class="note-link ${n.id===selectedNote?'active':''}" data-note="${esc(n.id)}"><b>${esc(n.title)}</b><small>${esc((n.body||'Empty note').slice(0,48))}</small></button>`).join('')||'<div class="empty"><p>No notes yet.</p></div>';let note=data.notes.find(n=>n.id===selectedNote);$('#noteEditor').innerHTML=note?`<input id="noteTitle" value="${esc(note.title)}" aria-label="Note title"><textarea id="noteBody" aria-label="Note body" placeholder="Start writing...">${esc(note.body)}</textarea><button class="danger" id="deleteNote">Delete note</button>`:'<div class="empty"><b>Select a note</b><p>Keep class notes and ideas together.</p></div>';if(note){let change=()=>{note.title=$('#noteTitle').value;note.body=$('#noteBody').value;note.updatedAt=new Date().toISOString();save()};$('#noteTitle').oninput=change;$('#noteBody').oninput=change;$('#deleteNote').onclick=()=>{if(confirm('Delete this note?')){data.notes=data.notes.filter(n=>n.id!==note.id);selectedNote=null;save(true);renderNotes()}}}}
function render(){if(!data)return;let old=$('#taskClassFilter').value;$('#taskClassFilter').innerHTML='<option value="">All classes</option>'+data.classes.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('');$('#taskClassFilter').value=old;renderDashboard();renderTasks();renderSchedule();renderClasses();renderNotes()}
function fields(type,x={}){if(type==='task')return `<div class="field-grid"><div class="field full"><label>Assignment name</label><input name="title" value="${esc(x.title||'')}" required autofocus></div><div class="field"><label>Class</label><select name="classId"><option value="">Personal</option>${data.classes.map(c=>`<option value="${esc(c.id)}" ${x.classId===c.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Due</label><input name="due" type="datetime-local" value="${esc((x.due||'').slice(0,16))}"></div><div class="field"><label>Priority</label><select name="priority">${['low','medium','high'].map(p=>`<option ${x.priority===p?'selected':''}>${p}</option>`).join('')}</select></div><div class="field full"><label>Details</label><textarea name="details" rows="5">${esc(x.details||'')}</textarea></div></div>`;
return `<div class="field-grid"><div class="field full"><label>Class name</label><input name="name" value="${esc(x.name||'')}" required autofocus></div><div class="field"><label>Code</label><input name="code" value="${esc(x.code||'')}"></div><div class="field"><label>Color</label><input name="color" type="color" value="${esc(x.color||'#5267ff')}"></div><div class="field"><label>Starts</label><input name="start" type="time" value="${esc(x.start||'09:00')}"></div><div class="field"><label>Ends</label><input name="end" type="time" value="${esc(x.end||'10:00')}"></div><div class="field"><label>Room</label><input name="room" value="${esc(x.room||'')}"></div><div class="field"><label>Instructor</label><input name="instructor" value="${esc(x.instructor||'')}"></div><div class="field full"><label>Meeting days</label><div class="days">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=>`<label><input type="checkbox" name="days" value="${d}" ${(x.days||[]).includes(d)?'checked':''}><span>${d[0]}</span></label>`).join('')}</div></div></div>`}
function openEditor(type,x){editing={type,id:x?.id};$('#modalKicker').textContent=x?'Edit':'New';$('#modalTitle').textContent=type==='task'?'Assignment':'Class';$('#editorFields').innerHTML=fields(type,x);$('#deleteItem').hidden=!x;$('#editorModal').hidden=false}
function closeEditor(){$('#editorModal').hidden=true;editing=null}
function submitEditor(e){e.preventDefault();let f=new FormData(e.target);if(editing.type==='task'){let old=data.tasks.find(t=>t.id===editing.id),x={id:editing.id||uid('task'),title:f.get('title'),classId:f.get('classId'),due:f.get('due'),priority:f.get('priority'),details:f.get('details'),completed:old?.completed||false,createdAt:old?.createdAt||new Date().toISOString()};data.tasks=data.tasks.filter(t=>t.id!==x.id);data.tasks.push(x)}else{let x={id:editing.id||uid('class'),name:f.get('name'),code:f.get('code'),color:f.get('color'),days:f.getAll('days'),start:f.get('start'),end:f.get('end'),room:f.get('room'),instructor:f.get('instructor')};data.classes=data.classes.filter(c=>c.id!==x.id);data.classes.push(x)}closeEditor();save(true);render();notify('Saved')}
function doSearch(q){q=q.toLowerCase();let rows=[];data.tasks.forEach(x=>(x.title+' '+x.details).toLowerCase().includes(q)&&rows.push(['Assignment',x.title,'tasks']));data.classes.forEach(x=>(x.name+' '+x.code).toLowerCase().includes(q)&&rows.push(['Class',x.name,'classes']));data.notes.forEach(x=>(x.title+' '+x.body).toLowerCase().includes(q)&&rows.push(['Note',x.title,'notes',x.id]));$('#searchResults').innerHTML=rows.slice(0,15).map((r,i)=>`<button class="search-result" data-result="${i}"><small>${esc(r[0])}</small><b>${esc(r[1])}</b></button>`).join('')||'<div class="empty"><p>No results</p></div>';$$('[data-result]').forEach(b=>b.onclick=()=>{let r=rows[+b.dataset.result];selectedNote=r[3]||selectedNote;$('#searchOverlay').hidden=true;changeView(r[2])})}
function aiMsg(role,text){let d=document.createElement('div');d.className='ai-message '+(role==='user'?'user':'bot');d.innerHTML='<p>'+esc(text).replace(/\n/g,'<br>')+'</p>';$('#aiMessages').append(d);$('#aiMessages').scrollTop=1e9}
async function ask(text){text=text.trim();if(!text)return;history.push({role:'user',content:text});aiMsg('user',text);$('#aiInput').value='';let wait=document.createElement('div');wait.className='ai-message bot';wait.textContent='Thinking…';$('#aiMessages').append(wait);try{let r=await fetch('/api/planner-ai',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify({messages:history})}),j=await r.json();if(!r.ok)throw new Error(j.error);wait.remove();history.push({role:'assistant',content:j.reply});aiMsg('assistant',j.reply)}catch(e){wait.textContent=e.message==='not_configured'?'Seehed needs GROQ_API_KEY configured.':'Seehed could not connect. Try again.'}}
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginError').textContent='';try{await request({action:'login',passcode:$('#passcode').value});let r=await request(null,'GET');data=r.data;$('#passcode').value='';openApp()}catch(x){$('#loginError').textContent=x.message==='invalid_passcode'?'That passcode is not correct.':x.message==='storage_not_configured'?'Connect planner storage in Vercel.':'Could not sign in.'}};
$('#logoutBtn').onclick=()=>request({action:'logout'}).finally(()=>location.reload());$('#menuBtn').onclick=()=>$('#app').classList.toggle('menu-open');$$('#nav button').forEach(b=>b.onclick=()=>changeView(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>changeView(b.dataset.go));$('#newTaskBtn').onclick=$('#quickTask').onclick=()=>openEditor('task');$('#newClassBtn').onclick=()=>openEditor('class');$$('[data-close]').forEach(b=>b.onclick=closeEditor);$('#editorForm').onsubmit=submitEditor;$('#deleteItem').onclick=()=>{if(editing&&confirm('Delete this item?')){data[editing.type==='task'?'tasks':'classes']=data[editing.type==='task'?'tasks':'classes'].filter(x=>x.id!==editing.id);closeEditor();save(true);render()}};$('#taskClassFilter').onchange=renderTasks;$$('#taskFilters button').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;$$('#taskFilters button').forEach(x=>x.classList.toggle('active',x===b));renderTasks()});
document.onclick=e=>{let b=e.target.closest('[data-check]');if(b){let t=data.tasks.find(x=>x.id===b.dataset.check);t.completed=!t.completed;save(true);render();return}if(b=e.target.closest('[data-edit-task]'))openEditor('task',data.tasks.find(x=>x.id===b.dataset.editTask));if(b=e.target.closest('[data-edit-class]'))openEditor('class',data.classes.find(x=>x.id===b.dataset.editClass));if(b=e.target.closest('[data-note]')){selectedNote=b.dataset.note;renderNotes()}};
$('#newNoteBtn').onclick=()=>{let n={id:uid('note'),title:'Untitled note',body:'',classId:'',updatedAt:new Date().toISOString()};data.notes.unshift(n);selectedNote=n.id;save(true);renderNotes()};$('#searchBtn').onclick=()=>{$('#searchOverlay').hidden=false;$('#globalSearch').value='';$('#globalSearch').focus();doSearch('')};$('#closeSearch').onclick=()=>$('#searchOverlay').hidden=true;$('#globalSearch').oninput=e=>doSearch(e.target.value);document.onkeydown=e=>{if(e.key==='/'&&!/input|textarea/i.test(document.activeElement.tagName)){e.preventDefault();$('#searchBtn').click()}if(e.key==='Escape'){$('#searchOverlay').hidden=true;closeEditor();$('#assistant').classList.remove('open')}};$('#aiBtn').onclick=()=>{$('#assistant').classList.add('open');$('#aiInput').focus()};$('#closeAi').onclick=()=>$('#assistant').classList.remove('open');$('#aiForm').onsubmit=e=>{e.preventDefault();ask($('#aiInput').value)};$$('.suggestions button').forEach(b=>b.onclick=()=>ask(b.textContent));initial();
})();
